---
- name: Project Module4 
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: Install Git
    yum: 
      name:
        - git 
      state: present
    become: yes 

  - name: Install Python3 
    yum: 
      name:
        - python3 
      version: 
      state: present 
    become: yes 

  - name: Install Poetry 
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      warn: no
      creates: /home/ec2-user/python3

  - name: Remove incorrect Directory 
    ansible.builtin.file: 
      state: absent
      path: /home/ec2-user/poetry

  - name: Create To-Do-App repo  
    ansible.builtin.file: 
      path: /opt/todoapp
      state: directory 
      mode: '777'
    become: yes

  - name: Pull Git Repo 
    ansible.builtin.git: 
      repo: https://github.com/adambird715/devopslearning.git
      dest: /opt/todoapp

  - name: Install Poetry Dependancies 
    ansible.builtin.shell: /home/ec2-user/.local/bin/poetry install 
    args: 
      chdir: /opt/todoapp 
      warn: no 
      
  - name: Create todoapp Service file
    ansible.builtin.file:
      path: "/etc/systemd/system/todoapp.service"
      mode: "777"
      state: touch  
    become: yes

  - name: Copy content into service file 
    ansible.builtin.copy:
      dest: "/etc/systemd/system/todoapp.service"
      content: |
        [Unit]
        Description=My To-Do-App

        [Service]
        User=ec2-user
        WorkingDirectory=/opt/todoapp
        ExecStart=/home/ec2-user/.local/bin/poetry run flask run --host 0.0.0.0
        ExecStop=/home/ec2-user/.local/bin/poetry 
    become: yes



  - name: Start TodoApp 
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes 
      name: todoapp.service
    become: yes